//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Homer : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerButton_Bool
        {
            get
            {
                return SteamVR_Actions.homer_TriggerButton_Bool;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerButton_Vector1
        {
            get
            {
                return SteamVR_Actions.homer_TriggerButton_Vector1;
            }
        }
        
        public virtual SteamVR_Action_Boolean SideButton_Bool
        {
            get
            {
                return SteamVR_Actions.homer_SideButton_Bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean UppderButton_Bool
        {
            get
            {
                return SteamVR_Actions.homer_UppderButton_Bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean LowerButton_Bool
        {
            get
            {
                return SteamVR_Actions.homer_LowerButton_Bool;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpad_Vector2
        {
            get
            {
                return SteamVR_Actions.homer_Touchpad_Vector2;
            }
        }
    }
}
